site_name: Xyndril Docs
site_url: https://maaninentupee.github.io/xyndril-lang/
repo_url: https://github.com/maaninentupee/xyndril-lang
repo_name: maaninentupee/xyndril-lang

# Material theme
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.action.edit
    - navigation.footer

extra:
  social:
    - icon: fontawesome/solid/envelope
      link: mailto:fusion@xyndril.dev
      name: "Contact: fusion@xyndril.dev"
nav:
  - Home: index.md
  - Language Spec: language-spec.md
  - Parser Spec: parser_spec.md
  - Usage Guide: usage.md
  - Workspace Setup: workspace-setup.md
  - Xyndril Manifest: xyndril-manifest.md
